# Project-level Gradle settings
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC
android.suppressUnsupportedCompileSdk=35

# React Native Configuration
hermesEnabled=true
newArchEnabled=false
reactNativeArchitectures=arm64-v8a

# CMake / Ninja Short Build Directory (Fixes Windows path spaces & MAX_PATH limit)
android.cxx.build.dir=C:/tmp/fic_cxx
android.overridePathCheck=true
